name: build lineage

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        lunch: ["lineage_sdk_phone_x86_64-eng"]
    runs-on: self-hosted
    timeout-minutes: 50400
    steps:
    - name: APT
      run: |
         sudo apt -y update
         sudo apt -y install bc            \
               ccache                      \
               coreutils                   \
               bison                       \
               build-essential             \
               curl                        \
               flex                        \
               g++-multilib                \
               gcc-multilib                \
               git                         \
               gnupg                       \
               gperf                       \
               lib32ncurses5-dev           \
               lib32readline-dev           \
               lib32z1-dev                 \
               zip                         \
               unzip                       \
               libsdl1.2-dev               \
               libssl-dev                  \
               libxml2                     \
               libxml2-utils               \
               lzop                        \
               pngcrush                    \
               rsync                       \
               schedtool                   \
               squashfs-tools              \
               xsltproc                    \
               zlib1g-dev                  \
               libncurses5                 \
               libncurses5-dev             \
               lib32z1-dev                 \
               libelf-dev                  \
               liblz4-tool                 \
               python3                     \
               python-is-python3           \
               android-sdk-platform-tools  \
               adb                         \
               fastboot                    \
               repo                        \
               default-jre                 \
               sdkmanager                  \
               android-sdk-libsparse-utils \
               imagemagick                 \
               git-lfs                     \
               tree
    - name: Directories
      run: mkdir -p bin && mkdir -p android/lineage && mkdir -p android-kernel
    - name: GIT LFS
      run: git lfs install
    - name: Repo Initialization (Lineage)
      working-directory: android/lineage
      if: ${{ hashFiles('WORKSPACE') == '' }}
      run: repo init -v -u https://github.com/LineageOS/android.git -b lineage-${{ vars.LINEAGE_VERSION }}
    - name: Repo Sync (Lineage)
      if: ${{ hashFiles('WORKSPACE') == '' }}
      working-directory: android/lineage
      run: repo sync -v -j$(nproc)
    - name: Repo Initialization (Android Kernel)
      if: ${{ hashFiles('WORKSPACE') == '' }}
      working-directory: android-kernel
      run: repo init -u https://android.googlesource.com/kernel/manifest -b common-android-mainline
    - name: Repo Sync (Android Kernel)
      if: ${{ hashFiles('WORKSPACE') == '' }}
      working-directory: android-kernel
      run: repo sync -j$(nproc)
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: Lunch
      working-directory: android/lineage
      run: source build/envsetup.sh && lunch ${{ matrix.lunch }}
    - name: Build
      working-directory: android/lineage
      run: source build/envsetup.sh && make -j$(nproc)
